import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { localeRegistry, SUPPORTED_LOCALES } from "../../locales/registry.ts";
import { MANIFEST_MESSAGE_KEYS, UI_MESSAGE_KEYS } from "../../locales/schema.ts";

export type GeneratedOutput = { relativePath: string; content: string };

export function messageParams(message: string) {
  return [...message.matchAll(/\{([A-Za-z][A-Za-z0-9]*)\}/g)]
    .map((match) => match[1])
    .sort((left, right) => left.localeCompare(right));
}

export function validateMessageSet(
  label: string,
  messages: Record<string, string>,
  expectedKeys: readonly string[],
  reference?: Record<string, string>,
) {
  const errors: string[] = [];
  const actualKeys = Object.keys(messages).sort((left, right) => left.localeCompare(right));
  const expected = [...expectedKeys].sort((left, right) => left.localeCompare(right));
  for (const key of expected) {
    if (!actualKeys.includes(key)) errors.push(`${label} is missing ${key}.`);
    else if (!messages[key].trim()) errors.push(`${label}/${key} must not be empty.`);
  }
  for (const key of actualKeys) {
    if (!expected.includes(key)) errors.push(`${label} contains unknown key ${key}.`);
  }
  if (reference) {
    for (const key of expected) {
      if (!messages[key] || !reference[key]) continue;
      const actualParams = messageParams(messages[key]);
      const referenceParams = messageParams(reference[key]);
      if (actualParams.join("\0") !== referenceParams.join("\0")) {
        errors.push(`${label}/${key} parameters must be ${referenceParams.join(", ") || "(none)"}.`);
      }
    }
  }
  return errors;
}

export function canonicalLocaleContent(locale: keyof typeof localeRegistry) {
  const entry = localeRegistry[locale];
  const combined = { ...entry.manifest, ...entry.ui };
  return Object.keys(combined)
    .sort((left, right) => left.localeCompare(right))
    .map((key) => `${key}\0${combined[key as keyof typeof combined]}\n`)
    .join("");
}

export function localeContentHash(locale: keyof typeof localeRegistry) {
  return createHash("sha256").update(canonicalLocaleContent(locale), "utf8").digest("hex");
}

function json(value: unknown) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function webExtensionMessages(messages: Record<string, string>) {
  return Object.fromEntries(
    Object.keys(messages)
      .sort((left, right) => left.localeCompare(right))
      .map((key) => [key, { message: messages[key] }]),
  );
}

function catalogSource() {
  const messages = Object.fromEntries(SUPPORTED_LOCALES.map((locale) => [locale, localeRegistry[locale].ui]));
  const displayNames = Object.fromEntries(SUPPORTED_LOCALES.map((locale) => [locale, localeRegistry[locale].displayName]));
  return `// Generated by scripts/i18n/generate.ts. Do not edit.\n`+
    `globalThis.PatinaLocaleCatalog = Object.freeze(${JSON.stringify({
      defaultLocale: "zh-CN",
      displayNames,
      messages,
    }, null, 2)});\n`;
}

export function renderDefaultHtml(template: string) {
  return template.replace(/\{\{([A-Za-z][A-Za-z0-9.-]+)\}\}/g, (_match, key: string) => {
    const value = (localeRegistry["zh-CN"].ui as Record<string, string>)[key];
    if (typeof value !== "string") throw new Error(`Unknown default HTML message token: ${key}.`);
    return value
      .replaceAll("&", "&amp;")
      .replaceAll("<", "&lt;")
      .replaceAll(">", "&gt;")
      .replaceAll('"', "&quot;");
  });
}

export async function buildGeneratedOutputs(repoRoot: string): Promise<GeneratedOutput[]> {
  const sharedFiles = [
    ["src/shared/background-status.js", "background-status.js"],
    ["src/shared/ui/platform.js", "platform.js"],
    ["src/shared/ui/i18n.js", "i18n.js"],
    ["src/shared/ui/options.html", "options.html"],
    ["src/shared/ui/options.js", "options.js"],
    ["src/shared/ui/popup.html", "popup.html"],
    ["src/shared/ui/popup.js", "popup.js"],
  ] as const;
  const contents = new Map<string, string>();
  for (const [source] of sharedFiles) contents.set(source, await readFile(join(repoRoot, source), "utf8"));

  const outputs: GeneratedOutput[] = [];
  for (const target of ["chromium", "firefox"] as const) {
    for (const [source, destination] of sharedFiles) {
      const content = contents.get(source) ?? "";
      outputs.push({
        relativePath: `src/${target}/${destination}`,
        content: destination.endsWith(".html") ? renderDefaultHtml(content) : content,
      });
    }
    outputs.push({ relativePath: `src/${target}/generated/messages.js`, content: catalogSource() });
    for (const locale of SUPPORTED_LOCALES) {
      const entry = localeRegistry[locale];
      outputs.push({
        relativePath: `src/${target}/_locales/${entry.webExtensionLocale}/messages.json`,
        content: json(webExtensionMessages(entry.manifest)),
      });
    }
  }
  return outputs.sort((left, right) => left.relativePath.localeCompare(right.relativePath));
}

export function validateRegistry() {
  const errors: string[] = [];
  const reference = localeRegistry["zh-CN"];
  for (const locale of SUPPORTED_LOCALES) {
    const entry = localeRegistry[locale];
    errors.push(...validateMessageSet(`${locale}/ui`, entry.ui, UI_MESSAGE_KEYS, reference.ui));
    errors.push(...validateMessageSet(`${locale}/manifest`, entry.manifest, MANIFEST_MESSAGE_KEYS, reference.manifest));
    if (!/^[a-z]{2}(?:_[A-Z]{2})?$/.test(entry.webExtensionLocale)) {
      errors.push(`${locale} has invalid WebExtension locale ${entry.webExtensionLocale}.`);
    }
  }
  if (new Set(SUPPORTED_LOCALES.map((locale) => localeRegistry[locale].webExtensionLocale)).size !== SUPPORTED_LOCALES.length) {
    errors.push("WebExtension locale mappings must be unique.");
  }
  return errors;
}
